services:
  healthchecker:
    build: .
    container_name: healthchecker
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN:-}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID:-}"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
